In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import pickle

In [9]:
data = pd.read_csv("F:\\Github_Desktop\\UNSUPERVISED-LEARNING-ALGORIDHAM\\mobile_recommendation_system_dataset copy.csv")
print("✅ Dataset Loaded Successfully!")
display(data.head())

✅ Dataset Loaded Successfully!

,name,ratings,price,imgURL,corpus
0,"REDMI Note 12 Pro 5G (Onyx Black, 128 GB)",4.2,23999,https://rukminim2.flixcart.com/image/312/312/x...,Storage128 GBRAM6 SystemAndroid 12Processor T...
1,"OPPO F11 Pro (Aurora Green, 128 GB)",4.5,"₹20,999",https://rukminim2.flixcart.com/image/312/312/k...,Storage128 GBRAM6 GBExpandable Storage256GB S...
2,"REDMI Note 11 (Starburst White, 64 GB)",4.2,13149,https://rukminim2.flixcart.com/image/312/312/x...,Storage64 GBRAM4 SystemAndroid 11Processor Sp...
3,"OnePlus Nord CE 5G (Blue Void, 256 GB)",4.1,21999,https://rukminim2.flixcart.com/image/312/312/x...,Storage256 GBRAM12 SystemAndroid Q 11Processo...
4,"APPLE iPhone 13 mini (Blue, 128 GB)",4.6,3537,https://rukminim2.flixcart.com/image/312/312/k...,Storage128 SystemiOS 15Processor TypeA15 Bion...

In [10]:
numeric_features = data.select_dtypes(include=['number']).columns.tolist()
print("Numeric Features:", numeric_features)

Numeric Features: ['ratings']

In [12]:
X = data[numeric_features]

In [13]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [15]:
k = 4   # you can change clusters later if needed
model = KMeans(n_clusters=k, random_state=42)
data['Cluster'] = model.fit_predict(X_scaled)
print("✅ Model Trained Successfully with", k, "clusters")

✅ Model Trained Successfully with 4 clusters

In [ ]:
with open("model.pkl", "wb") as file:
    pickle.dump((model, scaler, numeric_features), file)

print("✅ Model saved as model.pkl")

display(data.head())

✅ Model saved as model.pkl

,name,ratings,price,imgURL,corpus,Cluster
0,"REDMI Note 12 Pro 5G (Onyx Black, 128 GB)",4.2,23999,https://rukminim2.flixcart.com/image/312/312/x...,Storage128 GBRAM6 SystemAndroid 12Processor T...,0
1,"OPPO F11 Pro (Aurora Green, 128 GB)",4.5,"₹20,999",https://rukminim2.flixcart.com/image/312/312/k...,Storage128 GBRAM6 GBExpandable Storage256GB S...,1
2,"REDMI Note 11 (Starburst White, 64 GB)",4.2,13149,https://rukminim2.flixcart.com/image/312/312/x...,Storage64 GBRAM4 SystemAndroid 11Processor Sp...,0
3,"OnePlus Nord CE 5G (Blue Void, 256 GB)",4.1,21999,https://rukminim2.flixcart.com/image/312/312/x...,Storage256 GBRAM12 SystemAndroid Q 11Processo...,2
4,"APPLE iPhone 13 mini (Blue, 128 GB)",4.6,3537,https://rukminim2.flixcart.com/image/312/312/k...,Storage128 SystemiOS 15Processor TypeA15 Bion...,1